### ISSUE TITLE
I get File not found (winerror2)

### ISSUE THREAD

**Issue by pgh268400** [smacke/ffsubsync#103]
C:\>ffs 1.mkv -i 1.smi -o sync.smi
[02:15:16] INFO     extracting speech segments from reference '1.mkv'...                               ffsubsync.py:282
           INFO     Checking video for subtitles stream...                                   speech_transformers.py:172
           INFO     [WinError 2] 지정된 파일을 찾을 수 없습니다                              speech_transformers.py:177
           WARNING  [WinError 2] 지정된 파일을 찾을 수 없습니다                              speech_transformers.py:183
Traceback (most recent call last):
  File "c:\users\pgh26\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pgh26\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pgh26\AppData\Local\Programs\Python\Python38-32\Scripts\ffs.exe\__main__.py", line 9, in <module>
  File "c:\users\pgh26\appdata\local\programs\python\python38-32\lib\site-packages\ffsubsync\ffsubsync.py", line 387, in main
    return run(args)['retval']
  File "c:\users\pgh26\appdata\local\programs\python\python38-32\lib\site-packages\ffsubsync\ffsubsync.py", line 283, in run
    reference_pipe.fit(args.reference)
  File "c:\users\pgh26\appdata\local\programs\python\python38-32\lib\site-packages\ffsubsync\sklearn_shim.py", line 214, in fit
    self._final_estimator.fit(Xt, y, **fit_params)
  File "c:\users\pgh26\appdata\local\programs\python\python38-32\lib\site-packages\ffsubsync\speech_transformers.py", line 211, in fit
    process = subprocess.Popen(ffmpeg_args, **subprocess_args(include_stdout=True))
  File "c:\users\pgh26\appdata\local\programs\python\python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\pgh26\appdata\local\programs\python\python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다

C:\>

I worked on drive C and I get a File Not found error

The path is correct and the file exists

I did it on Windows 10, Python 3.8, and I get the same result when I do it on another Windows 10 computer

I want to know how to solve it..

**Comment by smacke** [comment]
@pgh268400, to help narrow down what the issue could be, could you let me know if it doesn't work with ascii filenames without whitespace? I'm wondering if it is struggling with the whitespace in the filename above. The Korean characters should be fine, but would be good to eliminate that as a source of problems as well.

**Comment by Mossa-D** [comment]
Hello. 

I read the other closed issues #64 and #39. Both had no clear indication of a solution, their problem appeared to have fix itself. Unfortunately not for me...

I have the same issue : `FileNotFoundError: [WinError 2] : File not found`.

ffs is running on a cmd prompt opened inside the directory where my episodes are located.

I am on Windows 10, python 3.8. It doesn't work with other files in other directories.

```
F:\Series\24\Season 3>subsync 24S03E23.mkv -i 24S03E23.srt -o 24S03E23_timed.srt
[22:32:33] INFO     extracting speech segments from reference '24S03E23.mkv'...                        ffsubsync.py:308
           INFO     Checking video for subtitles stream...                                   speech_transformers.py:177
           INFO     [WinError 2] Le fichier spécifié est introuvable                         speech_transformers.py:182
           WARNING  [WinError 2] Le fichier spécifié est introuvable                         speech_transformers.py:188
Traceback (most recent call last):
  File "c:\users\bob\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\bob\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\bob\AppData\Local\Programs\Python\Python38\Scripts\subsync.exe\__main__.py", line 7, in <module>
  File "c:\users\bob\appdata\local\programs\python\python38\lib\site-packages\ffsubsync\ffsubsync.py", line 415, in main
    return run(args)['retval']
  File "c:\users\bob\appdata\local\programs\python\python38\lib\site-packages\ffsubsync\ffsubsync.py", line 309, in run
    reference_pipe.fit(args.reference)
  File "c:\users\bob\appdata\local\programs\python\python38\lib\site-packages\ffsubsync\sklearn_shim.py", line 214, in fit
    self._final_estimator.fit(Xt, y, **fit_params)
  File "c:\users\bob\appdata\local\programs\python\python38\lib\site-packages\ffsubsync\speech_transformers.py", line 216, in fit
    process = subprocess.Popen(ffmpeg_args, **subprocess_args(include_stdout=True))
  File "c:\users\bob\appdata\local\programs\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\bob\appdata\local\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```

I have a different question that I don't believe is worth an issue, but is it possible to have a video and subtitle filename between quotations marks ? Most titles contains spaces or dashes, it's not compatible with the arguments calling.

**Comment by smacke** [comment]
I think both of these may be because ffmpeg is not on the search path. @Mossa-D could you confirm that the files are all in that directory and spelled correctly, and that ffmpeg is on the path?

**Comment by Mossa-D** [comment]
Problem solved ! 

The issue : ffmpeg was not in my system environment variables but not in my user environment variables.

The fix : **add ffmpeg to my user environment variables.**

It now works flawlessly, I tested it with multiple files in different folders (and it works now with quotation marks).

Thank you for your help and for your software 👍

**Comment by pgh268400** [comment]
> Problem solved !
> 
> The issue : ffmpeg was not in my system environment variables but not in my user environment variables.
> 
> The fix : **add ffmpeg to my user environment variables.**
> 
> It now works flawlessly, I tested it with multiple files in different folders (and it works now with quotation marks).
> 
> Thank you for your help and for your software 👍


This method worked for me too. Thank you.
I've actually synced the animation and it didn't work, but I'm happy to fix it anyway!

**Comment by smacke** [comment]
Great to hear things are at least running now! I'll go ahead and close out this issue.

@pgh268400, the latest master has some improvements to the sync algorithm -- you may have better luck with the sync if you install from there:

```
pip install git+https://github.com/smacke/ffsubsync@latest
```
