### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by VimWei** [smacke/ffsubsync#128]
**Environment (please complete the following information):**
 - OS: [Windows 10 Pro 20H2, x64]
 - python version (`3.9.5`)
 - subsync version (`subsync --version`)

**Describe the bug**

install ffsubsync `pip install ffsubsync`, but can't run any subsync command.

![2021-05-19_035455](https://user-images.githubusercontent.com/25874852/118715394-260cbf80-b856-11eb-8f96-950d1913d911.png)

**To Reproduce**

`subsync --version`

![2021-05-19_035639](https://user-images.githubusercontent.com/25874852/118715481-3c1a8000-b856-11eb-8f75-76ff76e461df.png)

`ffs Welcome.mp4 -i Welcome.srt -o WelcomeNew.srt`

![2021-05-19_035730](https://user-images.githubusercontent.com/25874852/118715581-5e140280-b856-11eb-9c43-c759bd5ccae3.png)

**Output**
```
Traceback (most recent call last):
  File "c:\users\chenw\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\chenw\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\chenw\AppData\Local\Programs\Python\Python39\Scripts\ffs.exe\__main__.py", line 4, in <module>
  File "c:\users\chenw\appdata\local\programs\python\python39\lib\site-packages\ffsubsync\__init__.py", line 21, in <module>
    from .ffsubsync import main  # noqa
  File "c:\users\chenw\appdata\local\programs\python\python39\lib\site-packages\ffsubsync\ffsubsync.py", line 14, in <module>
    from ffsubsync.aligners import FFTAligner, MaxScoreAligner, FailedToFindAlignmentException
  File "c:\users\chenw\appdata\local\programs\python\python39\lib\site-packages\ffsubsync\aligners.py", line 9, in <module>
    from ffsubsync.sklearn_shim import Pipeline, TransformerMixin
  File "c:\users\chenw\appdata\local\programs\python\python39\lib\site-packages\ffsubsync\sklearn_shim.py", line 12, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by dolohow** [comment]
For now you can do
```
pip install typing_extensions
```

**Comment by smacke** [comment]
Thanks @VimWei for filing the issue and @dolohow for the workaround. Apparently I forgot to add `typing_extensions` to `requirements.txt`, woops. Just pushed a fix, issue should be resolved after `pip install --upgrade ffsubsync`; please let me know if not.
