### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by dyphire** [smacke/ffsubsync#187]
**Environment (please complete the following information):**
 - OS: [Windows 11 23H2]
 - python version (python  3.12.2)
 - subsync version (`subsync --version`)

**Describe the bug**

install ffsubsync `pip install ffsubsync`, but can't run any subsync command.

**To Reproduce**

`subsync --version`

![image](https://github.com/smacke/ffsubsync/assets/61936050/9b80065b-32e7-451f-b062-85effe440a86)

**Output**
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "G:\Scoop\apps\python\current\Scripts\subsync.exe\__main__.py", line 4, in <module>
  File "G:\Scoop\apps\python\current\Lib\site-packages\ffsubsync\__init__.py", line 21, in <module>
    from .ffsubsync import main  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Scoop\apps\python\current\Lib\site-packages\ffsubsync\ffsubsync.py", line 34, in <module>
    from ffsubsync.speech_transformers import (
  File "G:\Scoop\apps\python\current\Lib\site-packages\ffsubsync\speech_transformers.py", line 11, in <module>
    import ffmpeg
  File "G:\Scoop\apps\python\current\Lib\site-packages\ffmpeg\__init__.py", line 2, in <module>
    from . import nodes
  File "G:\Scoop\apps\python\current\Lib\site-packages\ffmpeg\nodes.py", line 3, in <module>
    from past.builtins import basestring
  File "G:\Scoop\apps\python\current\Lib\site-packages\past\builtins\__init__.py", line 54, in <module>
    from past.builtins.misc import (apply, chr, cmp, execfile, intern, oct,
  File "G:\Scoop\apps\python\current\Lib\site-packages\past\builtins\misc.py", line 45, in <module>
    from imp import reload
ModuleNotFoundError: No module named 'imp'
```

**Comment by smacke** [comment]
This is an issue with Python 3.12; `imp` isn't supported there anymore but the `past` package still tried to import it at the time of this issue creation. You'll need to either try reinstalling python 3.12 or use an older version of python.
