### ISSUE TITLE
Not working on macOS

### ISSUE THREAD

**Issue by faxotherapy** [smacke/ffsubsync#205]
**Environment (please complete the following information):**
 - OS: macOS Monterey
 - python version: 3.12
 - subsync version (`subsync --version`): 0.17.0

**Describe the bug**
Crash right from the beginning.

**To Reproduce**
Simply run script under macOS

**Expected behavior**
Synced subtitle to be ouput.

**Output**
```
ffs Movie.mkv -i Movie.srt -o Movie_.srt
[23:09:48] INFO     extracting speech segments from reference 'Movie.mkv'...     ffsubsync.py:436
           INFO     Checking video for subtitles stream...                                                    speech_transformers.py:309
           INFO     Video file appears to lack subtitle stream                                                speech_transformers.py:314
Traceback (most recent call last):
  File "/Users/N/.local/bin/ffs", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/N/Library/Application Support/pipx/venvs/ffsubsync/lib/python3.12/site-packages/ffsubsync/ffsubsync.py", line 719, in main
    return run(parser)["retval"]
           ^^^^^^^^^^^
  File "/Users/N/Library/Application Support/pipx/venvs/ffsubsync/lib/python3.12/site-packages/ffsubsync/ffsubsync.py", line 501, in run
    sync_was_successful = _run_impl(args, result)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/N/Library/Application Support/pipx/venvs/ffsubsync/lib/python3.12/site-packages/ffsubsync/ffsubsync.py", line 437, in _run_impl
    reference_pipe.fit(args.reference)
  File "/Users/N/Library/Application Support/pipx/venvs/ffsubsync/lib/python3.12/site-packages/ffsubsync/sklearn_shim.py", line 255, in fit
    self._final_estimator.fit(Xt, y, **fit_params)
  File "/Users/N/Library/Application Support/pipx/venvs/ffsubsync/lib/python3.12/site-packages/ffsubsync/speech_transformers.py", line 333, in fit
    detector = _make_webrtcvad_detector(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/N/Library/Application Support/pipx/venvs/ffsubsync/lib/python3.12/site-packages/ffsubsync/speech_transformers.py", line 136, in _make_webrtcvad_detector
    import webrtcvad
  File "/Users/N/Library/Application Support/pipx/venvs/ffsubsync/lib/python3.12/site-packages/webrtcvad.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Test case**
[Optional] You can bundle additional debugging information into a tar archive as follows:
```
% subsync In.mkv -i In.srt -o Out.srt
unrecognized option 'In.mkv'
Traceback (most recent call last):
  File "subsync", line 6, in <module>
  File "subsync/__main__.py", line 16, in subsync
AttributeError: 'NoneType' object has no attribute 'get'
[66821] Failed to execute script 'subsync' due to unhandled exception: 'NoneType' object has no attribute 'get'
[66821] Traceback:
(null
```
This will create a file `vid.mkv.$timestamp.tar.gz` or similar a few KiB in size; you can attach it by clicking the "attach files" button below.

Obvious, it's failing again.

**Additional context**

**Comment by junkblocker** [comment]
Seems independent on the OS as I am seeing this on Fedora too.

**Comment by smacke** [comment]
Seems like the same thing as in https://github.com/smacke/ffsubsync/issues/203, could you try the remediation there and see if that works?

**Comment by junkblocker** [comment]
I did and it did not work. I already had setup tools installed.

**Comment by smacke** [comment]
`pkg_resources` is a package that's part of setuptools. I recommend verifying that it's installed in the same environment as ffsubsync. I'm going to add setuptools as an explicit dependency since it seems it doesn't come preinstalled in python 3.12 anymore, but you'll want to check that it's present.

To verify, you can run
```
ls "$(dirname $(which ffs))"/../lib/python3.12/site-packages
```
and if you don't see `pkg_resources` there, chances are you also won't see `setuptools` there, and the fix is to make sure setuptools gets installed to there.

**Comment by junkblocker** [comment]
I reinstalled it before seeing this. An install via uv tool seemed to have done something bad and remove and reinstall via pipx fixed it.

**Comment by smacke** [comment]
Glad to hear!
