### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [smacke/ffsubsync#76]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.3.7. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary ffsubsync -w /tmp/ext ffsubsync==0.3.7
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting ffsubsync==0.3.7
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/f47/d2993072bb291/ffsubsync-0.3.7.tar.gz (16 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ssachm44/ffsubsync/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ssachm44/ffsubsync/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ssachm44/ffsubsync/pip-egg-info
         cwd: /tmp/pip-wheel-ssachm44/ffsubsync/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ssachm44/ffsubsync/setup.py", line 13, in <module>
        history = read_file('HISTORY.rst')
      File "/tmp/pip-wheel-ssachm44/ffsubsync/setup.py", line 9, in read_file
        with open(fname, 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by smacke** [comment]
I admit I'm not super familiar with python packaging. I wonder why it's unhappy about HISTORY.rst but okay with README.md not being included -- weird!

(Maybe because it's assigned to a top-level variable? To be honest, I have no idea whether it's even necessary to read in HISTORY.rst -- this setup.py was copied from an example somewhere. Oh well!)

**Comment by thatch** [comment]
It's because `README.<foo>` is specialcased in setuptools.
