### ISSUE TITLE
Alpine Linux PIP installation error

### ISSUE THREAD

**Issue by nikolicjakov** [smacke/ffsubsync#78]
**Environment (please complete the following information):**
 - OS: Alpine Linux 3.11
 - python version 3.8.2

**Describe the bug**
I am getting pip installation errors when trying to install ffsubsync.

**To Reproduce**
Execute command `pip install ffsubsync`

**Expected behavior**
Installation is successful without errors.

**Output**
```
ERROR: Command errored out with exit status 1:
    command: /usr/bin/python3.8 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-zrkvvub3/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation == '"'"'CPython'"'"'' 'numpy==1.14.0; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation != '"'"'CPython'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'scipy>=0.19.1'
        cwd: None
   Complete output (171 lines):
   Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX" and platform_python_implementation == "CPython"' don't match your environment
   Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX" and platform_python_implementation != "CPython"' don't match your environment
   Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
   Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
   Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
   Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
   Collecting setuptools
     Downloading https://files.pythonhosted.org/packages/95/95/f657b6e17f00c3f35b5f68b10e46c3a43af353d8856bd57bfcfb1dbb3e92/setuptools-47.1.1-py3-none-any.whl (583kB)
   Collecting wheel
     Downloading https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
   Collecting Cython>=0.28.5
     Downloading https://files.pythonhosted.org/packages/ba/b7/00ef671f74ee4694de58d88101e6f9a655cb8009e37a66a57f19642ff5d6/Cython-0.29.19-py2.py3-none-any.whl (971kB)
   Collecting numpy==1.17.3
     Downloading https://files.pythonhosted.org/packages/b6/d6/be8f975f5322336f62371c9abeb936d592c98c047ad63035f1b38ae08efe/numpy-1.17.3.zip (6.4MB)
   Collecting scipy>=0.19.1
     Downloading https://files.pythonhosted.org/packages/04/ab/e2eb3e3f90b9363040a3d885ccc5c79fe20c5b8a3caa8fe3bf47ff653260/scipy-1.4.1.tar.gz (24.6MB)
     Installing build dependencies: started
     Installing build dependencies: still running...
     Installing build dependencies: still running...
     Installing build dependencies: finished with status 'done'
     Getting requirements to build wheel: started
     Getting requirements to build wheel: finished with status 'done'
       Preparing wheel metadata: started
       Preparing wheel metadata: finished with status 'error'
       ERROR: Command errored out with exit status 1:
        command: /usr/bin/python3.8 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp4u01hbfx
            cwd: /tmp/pip-install-gn76wi04/scipy
       Complete output (139 lines):
       lapack_opt_info:
       lapack_mkl_info:
       customize UnixCCompiler
         libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
         NOT AVAILABLE
   
       openblas_lapack_info:
       customize UnixCCompiler
       customize UnixCCompiler
         libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
         NOT AVAILABLE
   
       openblas_clapack_info:
       customize UnixCCompiler
       customize UnixCCompiler
         libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
         NOT AVAILABLE
   
       flame_info:
       customize UnixCCompiler
         libraries flame not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
         NOT AVAILABLE
   
       atlas_3_10_threads_info:
       Setting PTATLAS=ATLAS
       customize UnixCCompiler
         libraries lapack_atlas not found in /usr/local/lib
       customize UnixCCompiler
         libraries tatlas,tatlas not found in /usr/local/lib
       customize UnixCCompiler
         libraries lapack_atlas not found in /usr/lib
       customize UnixCCompiler
         libraries tatlas,tatlas not found in /usr/lib
       customize UnixCCompiler
         libraries lapack_atlas not found in /usr/lib/
       customize UnixCCompiler
         libraries tatlas,tatlas not found in /usr/lib/
       <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
         NOT AVAILABLE
   
       atlas_3_10_info:
       customize UnixCCompiler
         libraries lapack_atlas not found in /usr/local/lib
       customize UnixCCompiler
         libraries satlas,satlas not found in /usr/local/lib
       customize UnixCCompiler
         libraries lapack_atlas not found in /usr/lib
       customize UnixCCompiler
         libraries satlas,satlas not found in /usr/lib
       customize UnixCCompiler
         libraries lapack_atlas not found in /usr/lib/
       customize UnixCCompiler
         libraries satlas,satlas not found in /usr/lib/
       <class 'numpy.distutils.system_info.atlas_3_10_info'>
         NOT AVAILABLE
   
       atlas_threads_info:
       Setting PTATLAS=ATLAS
       customize UnixCCompiler
         libraries lapack_atlas not found in /usr/local/lib
       customize UnixCCompiler
         libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
       customize UnixCCompiler
         libraries lapack_atlas not found in /usr/lib
       customize UnixCCompiler
         libraries ptf77blas,ptcblas,atlas not found in /usr/lib
       customize UnixCCompiler
         libraries lapack_atlas not found in /usr/lib/
       customize UnixCCompiler
         libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
       <class 'numpy.distutils.system_info.atlas_threads_info'>
         NOT AVAILABLE
   
       atlas_info:
       customize UnixCCompiler
         libraries lapack_atlas not found in /usr/local/lib
       customize UnixCCompiler
         libraries f77blas,cblas,atlas not found in /usr/local/lib
       customize UnixCCompiler
         libraries lapack_atlas not found in /usr/lib
       customize UnixCCompiler
         libraries f77blas,cblas,atlas not found in /usr/lib
       customize UnixCCompiler
         libraries lapack_atlas not found in /usr/lib/
       customize UnixCCompiler
         libraries f77blas,cblas,atlas not found in /usr/lib/
       <class 'numpy.distutils.system_info.atlas_info'>
         NOT AVAILABLE
   
       accelerate_info:
         NOT AVAILABLE
   
       lapack_info:
       customize UnixCCompiler
         libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
         NOT AVAILABLE
   
       lapack_src_info:
         NOT AVAILABLE
   
         NOT AVAILABLE
   
       setup.py:418: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-install-gn76wi04/scipy/pip-wheel-metadata'), proceeding with generating Cython sources and expanding templates
         warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
       Running from scipy source directory.
       /tmp/pip-build-env-v1lirlyh/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
           Lapack (http://www.netlib.org/lapack/) libraries not found.
           Directories to search for the libraries can be specified in the
           numpy/distutils/site.cfg file (section [lapack]) or by setting
           the LAPACK environment variable.
         if getattr(self, '_calc_info_{}'.format(lapack))():
       /tmp/pip-build-env-v1lirlyh/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
           Lapack (http://www.netlib.org/lapack/) sources not found.
           Directories to search for the sources can be specified in the
           numpy/distutils/site.cfg file (section [lapack_src]) or by setting
           the LAPACK_SRC environment variable.
         if getattr(self, '_calc_info_{}'.format(lapack))():
       Traceback (most recent call last):
         File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
           main()
         File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
           json_out['return_val'] = hook(**hook_input['kwargs'])
         File "/usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
           return hook(metadata_directory, config_settings)
         File "/tmp/pip-build-env-v1lirlyh/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 158, in prepare_metadata_for_build_wheel
           self.run_setup()
         File "/tmp/pip-build-env-v1lirlyh/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 249, in run_setup
           super(_BuildMetaLegacyBackend,
         File "/tmp/pip-build-env-v1lirlyh/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in run_setup
           exec(compile(code, __file__, 'exec'), locals())
         File "setup.py", line 540, in <module>
           setup_package()
         File "setup.py", line 536, in setup_package
           setup(**metadata)
         File "/tmp/pip-build-env-v1lirlyh/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
           config = configuration()
         File "setup.py", line 435, in configuration
           raise NotFoundError(msg)
       numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
       ----------------------------------------
   ERROR: Command errored out with exit status 1: /usr/bin/python3.8 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp4u01hbfx Check the logs for full command output.
   WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
   You should consider upgrading via the 'pip install --upgrade pip' command.
   ----------------------------------------
 ERROR: Command errored out with exit status 1: /usr/bin/python3.8 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-zrkvvub3/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation == '"'"'CPython'"'"'' 'numpy==1.14.0; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation != '"'"'CPython'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'scipy>=0.19.1' Check the logs for full command output.
 WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
 You should consider upgrading via the 'pip install --upgrade pip' command.
 The command '/bin/sh -c pip3 install ffsubsync' returned a non-zero code: 1
```

**Comment by smacke** [comment]
Hi @nikolicjakov, this is because of the scipy dependency, which some Linux distros have trouble grabbing. I plan to push a new version which removes the scipy dependency later today; once I do, could I ask for your help testing the install process?

**Comment by nikolicjakov** [comment]
Hi @smacke, i would be more than happy to test it out. Just let me know when i can start my build pipeline 👍

**Comment by smacke** [comment]
OK @nikolicjakov, I implemented the fix a bit later than originally planned but it should be available now: `pip install --upgrade ffsubsync`. Please let me know if the new version without sklearn works for you!

**Comment by nikolicjakov** [comment]
My build was successful meaning that pip installation is working. Now i need to test run my bazzar image and see ffsubsync in action.

**Comment by smacke** [comment]
Glad to hear it!
