### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by sevospl** [smacke/ffsubsync#85]
Subtitles sent by e-mail :)

```
Traceback (most recent call last):
  File "/root/subsync/bin/ffsubsync", line 8, in <module>
    sys.exit(main())
  File "/root/subsync/lib/python3.6/site-packages/ffsubsync/ffsubsync.py", line 260, in main
    return run(args)
  File "/root/subsync/lib/python3.6/site-packages/ffsubsync/ffsubsync.py", line 145, in run
    out_subs.write_file(args.srtout)
  File "/root/subsync/lib/python3.6/site-packages/ffsubsync/generic_subtitles.py", line 126, in write_file
    out_format = os.path.splitext(fname)[-1][1:]
  File "/root/subsync/lib/python3.6/posixpath.py", line 122, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by smacke** [comment]
Hey,

Thanks for this. I forgot to test setting the output format when writing to stdout. It should work if you use the `-o` flag instead of redirecting to a file, but I also pushed a quick fix: `pip install --upgrade ffsubsync`. Note that we use the same format as the input subtitles since we don't get the output filename as an argument when doing stdout redirection (and therefore can't pick an output format based on the file extension).
