### ISSUE TITLE
Cannot use `--make-test-case` with `--overwrite-input`

### ISSUE THREAD

**Issue by morpheus65535** [smacke/ffsubsync#91]
https://github.com/smacke/ffsubsync/blob/997749de8aac74ec19137a2e641b97ef1bba81ea/ffsubsync/ffsubsync.py#L205

shouldn't it be:

`if args.srtin is None or (args.srtout is None and args.overwrite_input is None):`

**Comment by morpheus65535** [comment]
Something else seems to be wrong because I get this error now (even if I replace `--overwrite-input` by `-o`:
```
Traceback (most recent call last):
  File "c:\\users\\morpheus\\desktop\\bazarr\\bazarr\\subsyncer.py", line 49, in sync
    result = run(self.args)
  File "c:\\users\\morpheus\\desktop\\bazarr\\bazarr\\../libs\\ffsubsync\\ffsubsync.py", line 289, in run
    result[\'retval\'] += make_test_case(args, npy_savename, sync_was_successful)
  File "c:\\users\\morpheus\\desktop\\bazarr\\bazarr\\../libs\\ffsubsync\\ffsubsync.py", line 47, in make_test_case
    os.mkdir(tar_dir)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: \'Z:\\\\Series TV\\\\The 100\\\\Season 7\\\\The.100.S07E11.720p.HDTV.x264-SVA[rarbg].mkv.2020-08-18-00:08:46\''
```

**Comment by morpheus65535** [comment]
As `args.strout` is required down the road to copy it to the tar.gz archive, we cannot use `args.overwrite_input` with `--make-test-case`. I finally had to make a temporary output file and, when sync succeed, delete original and rename synced subtitles.
